// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-FDfe-0u_5CTmNzwz6Eps9bmMnunY1Yc',
    appId: '1:121758559763:web:08e44105a1269af9aa99e6',
    messagingSenderId: '121758559763',
    projectId: 'fir-project-1-a1f1e',
    authDomain: 'fir-project-1-a1f1e.firebaseapp.com',
    storageBucket: 'fir-project-1-a1f1e.firebasestorage.app',
    measurementId: 'G-BS0SY1ZZST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjCpi8xvrAvdt8q7AYPkkidZvKULGjYcU',
    appId: '1:121758559763:android:54ad5ec4a40318aaaa99e6',
    messagingSenderId: '121758559763',
    projectId: 'fir-project-1-a1f1e',
    storageBucket: 'fir-project-1-a1f1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQijoF9mzCc4BGnejnC2Q_JIUmrkXFRgU',
    appId: '1:121758559763:ios:d700ebd01982edfaaa99e6',
    messagingSenderId: '121758559763',
    projectId: 'fir-project-1-a1f1e',
    storageBucket: 'fir-project-1-a1f1e.firebasestorage.app',
    iosBundleId: 'com.example.babyShopHub',
  );
}
